In [1]:
import pandas as pd
import numpy as np

In [2]:
#Caracteristicas generales, seguridad social y eduacción 
#Listas a los conjuntos de datos
url_cgsse = "https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/cgsse.CSV"
url_ocupados = "https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV"
url_ft = "https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV"
url_desocupados = "https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV"

# CGSSE
df_cgsse = pd.read_csv(url_cgsse, encoding='latin-1', sep=';', 
                       low_memory=False)

#Ocupados
df_ocupados=pd.read_csv(url_ocupados,encoding='latin-1',sep=';',
                        low_memory=False)

#Fuerza de trabajo
df_ft=pd.read_csv(url_ft,
                  encoding='latin-1',sep=';',low_memory=False)
#No ocupados
df_desocupados=pd.read_csv(url_desocupados,encoding='latin-1',
                           sep=';',low_memory=False)

In [3]:
df_cgsse

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250626,6,2025,8238974,1,1,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
1,20250626,6,2025,8238974,1,2,1,10,NaN,2,...,2.0,NaN,5.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0
2,20250626,6,2025,8238975,1,1,1,10,NaN,2,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
3,20250626,6,2025,8238975,1,2,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
4,20250626,6,2025,8238975,1,3,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67851,20250626,6,2025,8283060,1,1,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
67852,20250626,6,2025,8283060,1,2,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
67853,20250626,6,2025,8283062,1,1,1,10,94.0,1,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
67854,20250626,6,2025,8283062,1,2,1,10,94.0,1,...,2.0,NaN,3.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0
67855,20250626,6,2025,8283062,1,3,1,10,94.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0

In [4]:
df_ft

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P3362S8,P3362S7A1,P6300,P6310,P6310S1,P6320,P6330,P6340,P6350,P6351
0,20250626,6,2025,8238974,1,1,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20250626,6,2025,8238974,1,2,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20250626,6,2025,8238975,1,1,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20250626,6,2025,8238975,1,2,1,50,NaN,2,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20250626,6,2025,8238975,1,3,1,50,NaN,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54445,20250626,6,2025,8283060,1,1,1,50,88.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54446,20250626,6,2025,8283060,1,2,1,50,88.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54447,20250626,6,2025,8283062,1,1,1,50,94.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54448,20250626,6,2025,8283062,1,2,1,50,94.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54449,20250626,6,2025,8283062,1,3,1,50,94.0,1,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#1. Para el total nacional calcule :
#-población total 
#-población en edad de trabajar
#-población que no está en edad de trabajar
#-población económicamente activa 
#-población económicamente inactiva
#-tasa de ocupación 
#-tasa de desempleo

In [32]:
#POBLACIÓN TOTAL 
PT =  df_cgsse['FEX_C18'].sum()
print(f' La población total de qeureferencia al pais colombia Colombia es de {PT} personas')

 La población total de qeureferencia al pais colombia Colombia es de 52045001.000009045 personas

In [33]:
#POBLACION EN EDAD DE TRABAJAR 
PET = df_cgsse[(df_cgsse['P6040']>=15)]['FEX_C18'].sum()
print(f" La población en edad de trabajar (mayor o iguales a 15 años) para Colombia es de {PET} ")

 La población en edad de trabajar (mayor o iguales a 15 años) para Colombia es de 40653416.00000409

In [34]:
#POBLACIÓN QUE NO ESTA EN EDAD DE TRABAJAR 
PENT = df_cgsse[(df_cgsse['P6040'] < 15)]['FEX_C18'].sum() 
print(f" La población que no esta en edad de trabajar (menores de 15 años) para Colombia es de {PENT} personas ")

 La población que no esta en edad de trabajar (menores de 15 años) para Colombia es de 11391585.000004958 personas

In [37]:
#POBLACIÓN ECONOMICAMENTE ACTIVA
PEA=df_ft[(df_ft['FT']==1)]['FEX_C18'].sum()
print(f'Población Economicamente Activa (PEA) para colombia es de {PEA} personas')

Población Economicamente Activa (PEA) para colombia es de 25974846.22356785 personas

In [38]:
#POBLACIÓN ECONOMICAMENTE INACTIVA
PEI=df_ft[(df_ft['FFT']==1)]['FEX_C18'].sum()
print(f'Población Economicamente Inactiva(PEI) para colombia es de {PEI} personas')

Población Economicamente Inactiva(PEI) para colombia es de 14678569.776436238 personas

In [40]:
#TASA DE OCUPADOS
O=df_ocupados[(df_ocupados['OCI']==1)]['FEX_C18'].sum()
print(f'la poblacion ocupadaen colombia es de {O} personas')
TO = O/PET
print(f'la Tasa de Ocupacion, calculada como la poblacion ocupada (o)dividida entre lapoblacion en edad de trabajar es del : {TO:.2%}')

la poblacion ocupadaen colombia es de 23752952.660255846 personas
la Tasa de Ocupacion, calculada como la poblacion ocupada (o)dividida entre lapoblacion en edad de trabajar es del : 58.43%

In [41]:
#TASA DE DESEMPLEO
D=df_desocupados[(df_desocupados['DSI']==1)]['FEX_C18'].sum()
print(f'la Población Desocupada para colombia es de {D} personas')
TD = D/PEA
print(f'la Tasa de Desempleo (TD), calculada como la poblacion desocupada(D), dividida entre la poblacion economicament activa (PEA) es de: {TD:.2%}')

la Población Desocupada para colombia es de 2221893.563312005 personas
la Tasa de Desempleo (TD), calculada como la poblacion desocupada(D), dividida entre la poblacion economicament activa (PEA) es de: 8.55%

In [ ]:
#  2. Calcule las tasas de desempleo para hombres y mujeres en Risaralda, Caldas , Tolima y Quindío. ¿Cuál es el departamento con mayor y menor tasa de desempleo de los 4 ?

In [13]:
df_d = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV'
                       ,encoding='latin',sep=';')

In [14]:
#Primero hay que anexar la p3271 a la tabla de desempleados
df_d = pd.merge(df_d, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271','P6040']], 
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

df_ft = pd.merge(df_ft, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271','P6040']], 
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

In [15]:
# 1. Calcular cantidad de hombres desempleados en Risaralda
HDQ = df_d[(df_d['DSI']==1) & (df_d['DPTO']==66) & (df_d['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleados en Risaralda: {HDQ}')
# Calcular cantidad de mujeres desempleadas en Risaralda
HDQ2 = df_d[(df_d['DSI']==1) & (df_d['DPTO']==66) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en Risaralda: {HDQ2}')

# 2. Calcular cantidad de hombres en la PEA del Risaralda
PEAHQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==66) & (df_ft['P3271']==1) ]['FEX_C18'].sum()
# Calcular cantidad de mujeres en la PEA del Risaralda
PEAHQ2 = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==66) & (df_ft['P3271']==2) ]['FEX_C18'].sum()


# 3. Calcular la tasa de desempleo en hombres del Risaralda
TDHQ = HDQ/PEAHQ
print(f'Tasa de Desempleo en hombres del Risaralda: {TDHQ:.2%}')
# Calcular la tasa de desempleo en mujeres del Risaralda
TDHQ2 = HDQ2/PEAHQ2
print(f'Tasa de Desempleo en mujeres del Risaralda: {TDHQ2:.2%}')

Hombres Desempleados en Risaralda: 18000.60370715
Mujeres Desempleadas en Risaralda: 21676.799766712
Tasa de Desempleo en hombres del Risaralda: 6.07%
Tasa de Desempleo en mujeres del Risaralda: 10.67%

In [16]:
# 1. Calcular cantidad de hombres desempleados en Quindio
HDQ = df_d[(df_d['DSI']==1) & (df_d['DPTO']==63) & (df_d['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleados en Quindio: {HDQ}')
# Calcular cantidad de mujeres desempleadas en Quindio
HDQ2 = df_d[(df_d['DSI']==1) & (df_d['DPTO']==63) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en Quindio: {HDQ2}')

# 2. Calcular cantidad de hombres en la PEA del Quindio
PEAHQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==63) & (df_ft['P3271']==1) ]['FEX_C18'].sum()
# Calcular cantidad de mujeres en la PEA del Quindio
PEAHQ2 = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==63) & (df_ft['P3271']==2) ]['FEX_C18'].sum()


# 3. Calcular la tasa de desempleo en hombres del Quindio
TDHQ = HDQ/PEAHQ
print(f'Tasa de Desempleo en hombres del Quindio: {TDHQ:.2%}')
# Calcular la tasa de desempleo en mujeres del Quindio
TDHQ2 = HDQ2/PEAHQ2
print(f'Tasa de Desempleo en mujeres del Quindio: {TDHQ2:.2%}')

Hombres Desempleados en Quindio: 17869.520960767004
Mujeres Desempleadas en Quindio: 10618.534945967001
Tasa de Desempleo en hombres del Quindio: 10.23%
Tasa de Desempleo en mujeres del Quindio: 9.08%

In [17]:
# 1. Calcular cantidad de hombres desempleados en Tolima
HDQ = df_d[(df_d['DSI']==1) & (df_d['DPTO']==73) & (df_d['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleados en Tolima: {HDQ}')
# Calcular cantidad de mujeres desempleadas en Tolima
HDQ2 = df_d[(df_d['DSI']==1) & (df_d['DPTO']==73) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en Tolima: {HDQ2}')

# 2. Calcular cantidad de hombres en la PEA del Tolima
PEAHQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==73) & (df_ft['P3271']==1) ]['FEX_C18'].sum()
# Calcular cantidad de mujeres en la PEA del Tolima
PEAHQ2 = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==73) & (df_ft['P3271']==2) ]['FEX_C18'].sum()


# 3. Calcular la tasa de desempleo en hombres del Tolima
TDHQ = HDQ/PEAHQ
print(f'Tasa de Desempleo en hombres del Tolima: {TDHQ:.2%}')
# Calcular la tasa de desempleo en mujeres del Tolima
TDHQ2 = HDQ2/PEAHQ2
print(f'Tasa de Desempleo en mujeres del Tolima: {TDHQ2:.2%}')

Hombres Desempleados en Tolima: 28255.96613253
Mujeres Desempleadas en Tolima: 52100.16756370999
Tasa de Desempleo en hombres del Tolima: 7.22%
Tasa de Desempleo en mujeres del Tolima: 19.20%

In [18]:
# 1. Calcular cantidad de hombres desempleados en Caldas
HDQ = df_d[(df_d['DSI']==1) & (df_d['DPTO']==17) & (df_d['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleados en Caldas: {HDQ}')
# Calcular cantidad de mujeres desempleadas en Caldas
HDQ2 = df_d[(df_d['DSI']==1) & (df_d['DPTO']==17) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en Caldas: {HDQ2}')

# 2. Calcular cantidad de hombres en la PEA del Caldas
PEAHQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==17) & (df_ft['P3271']==1) ]['FEX_C18'].sum()
# Calcular cantidad de mujeres en la PEA del Caldas
PEAHQ2 = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==17) & (df_ft['P3271']==2) ]['FEX_C18'].sum()


# 3. Calcular la tasa de desempleo en hombres del Caldas
TDHQ = HDQ/PEAHQ
print(f'Tasa de Desempleo en hombres del Caldas: {TDHQ:.2%}')
# Calcular la tasa de desempleo en mujeres del Caldas
TDHQ2 = HDQ2/PEAHQ2
print(f'Tasa de Desempleo en mujeres del Caldas: {TDHQ2:.2%}')

Hombres Desempleados en Caldas: 18226.160047418998
Mujeres Desempleadas en Caldas: 17214.491449226003
Tasa de Desempleo en hombres del Caldas: 5.58%
Tasa de Desempleo en mujeres del Caldas: 7.68%

In [ ]:
# Al observar las tasas de desempleo de los 4 depatamentos, el mayor depatamento con mayor tasa de desempleo es el Quindio con un 10.23% en los hombres y en las mujeres es de 9.08%
# Mientras que el departamento con menor tasa de desempleo es caldas con un 5.58% en los hombres y en lasmujeres un 7.68%

In [ ]:
#3.Tomando en consideración únicamente los siguientes grupos de edad:
#18 a 24, 24 a 30, 30 a 40, 40 a 50,
#60 en adelante
#Para Risaralda, Caldas , Tolima y Quindío, cual es el grupo de edad con mayor y menor tasa de desempleo (indicar en cada departamento el grupo de de edad con mayor y menor tasa de desempleo) ?

In [19]:
#Segmento de edad en en Quindio

# 1. Calcular cantidad personas desempleadas entre los 18 - 24 
D1824Q = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==63)]['FEX_C18'].sum()

D2430Q = df_d[(df_d['DSI']==1) & (df_d['P6040']>=24) & (df_d['P6040']<=30) & (df_d['DPTO']==63)]['FEX_C18'].sum()

D3040Q = df_d[(df_d['DSI']==1) & (df_d['P6040']>=30) & (df_d['P6040']<=40) & (df_d['DPTO']==63)]['FEX_C18'].sum()

D4050Q = df_d[(df_d['DSI']==1) & (df_d['P6040']>=40) & (df_d['P6040']<=50) & (df_d['DPTO']==63)]['FEX_C18'].sum()

D60Q = df_d[(df_d['DSI']==1) & (df_d['P6040']>=60) & (df_d['DPTO']==63)]['FEX_C18'].sum()

# 2. Calcular cantidad personas en la PEA en Quindio

PEA1824Q = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==63)]['FEX_C18'].sum()

PEA2430Q = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==63)]['FEX_C18'].sum()

PEA3040Q = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==63)]['FEX_C18'].sum()

PEA4050Q = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==63)]['FEX_C18'].sum()

PEA60Q = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==63)]['FEX_C18'].sum()

# 3. Calcular la tasa de desempleo en Quindio

print(f'=======Tasa de desempleo en Quindio=======')

TD1824Q = D1824Q/PEA1824Q
print(f'Tasa de Desempleo en personas entre los 18 - 24 del Quindio: {TD1824Q:.2%}')

TD2430Q = D2430Q/PEA2430Q
print(f'Tasa de Desempleo en personas entre los 24 - 30 del Quindio: {TD2430Q:.2%}%')

TD3040Q = D3040Q/PEA3040Q
print(f'Tasa de Desempleo en personas entre los 30 - 40 del Quindio: {TD3040Q:.2%}')

TD4050Q = D4050Q/PEA4050Q
print(f'Tasa de Desempleo en personas entre los 40 - 50 del Quindio: {TD4050Q:.2%}')

TD60Q = D60Q/PEA60Q
print(f'Tasa de Desempleo en personas mayores a 60 del Quindio: {TD60Q:.2%}\n')

=======Tasa de desempleo en Quindio=======
Tasa de Desempleo en personas entre los 18 - 24 del Quindio: 12.77%
Tasa de Desempleo en personas entre los 24 - 30 del Quindio: 13.71%%
Tasa de Desempleo en personas entre los 30 - 40 del Quindio: 9.65%
Tasa de Desempleo en personas entre los 40 - 50 del Quindio: 6.26%
Tasa de Desempleo en personas mayores a 60 del Quindio: 10.31%

In [ ]:
#la tasa de desempleo mas alta del Quindio se encuentra en el grupo 24-30 años (13.71%) 
#la tasa con menores tasa de desempleo son los de 40-50 años (6.26%)

In [20]:
#Segmento de edad en Risaralda

# 1. Calcular cantidad personas desempleadas entre los 18 - 24 
D1824R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==66)]['FEX_C18'].sum()

D2430R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=24) & (df_d['P6040']<=30) & (df_d['DPTO']==66)]['FEX_C18'].sum()

D3040R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=30) & (df_d['P6040']<=40) & (df_d['DPTO']==66)]['FEX_C18'].sum()

D4050R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=40) & (df_d['P6040']<=50) & (df_d['DPTO']==66)]['FEX_C18'].sum()

D60R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=60) & (df_d['DPTO']==66)]['FEX_C18'].sum()

# 2. Calcular cantidad personas en la PEA en Risaralda

PEA1824R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

PEA2430R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

PEA3040R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

PEA4050R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

PEA60R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==66)]['FEX_C18'].sum()

# 3. Calcular la tasa de desempleo en Risaralda

print(f'=======Tasa de desempleo en Risaralda=======')

TD1824R = D1824R/PEA1824R
print(f'Tasa de Desempleo en personas entre los 18 - 24 del Risaralda: {TD1824R:.2%}')

TD2430R = D2430R/PEA2430R
print(f'Tasa de Desempleo en personas entre los 24 - 30 del Risaralda: {TD2430R:.2%}%')

TD3040R = D3040R/PEA3040R
print(f'Tasa de Desempleo en personas entre los 30 - 40 del Risaralda: {TD3040R:.2%}')

TD4050R = D4050R/PEA4050R
print(f'Tasa de Desempleo en personas entre los 40 - 50 del Risaralda: {TD4050R:.2%}')

TD60R = D60R/PEA60R
print(f'Tasa de Desempleo en personas mayores a 60 del Risaralda: {TD60R:.2%}\n')

=======Tasa de desempleo en Risaralda=======
Tasa de Desempleo en personas entre los 18 - 24 del Risaralda: 14.79%
Tasa de Desempleo en personas entre los 24 - 30 del Risaralda: 11.58%%
Tasa de Desempleo en personas entre los 30 - 40 del Risaralda: 6.45%
Tasa de Desempleo en personas entre los 40 - 50 del Risaralda: 7.34%
Tasa de Desempleo en personas mayores a 60 del Risaralda: 3.64%

In [ ]:
#la tasa de desempelo mas alta de Risaralda se encuentra el grupo 18-24 años (14.79%) 
#la tasa con menor tasa de desempleo son los mayores de 60 años (3.64%)

In [21]:
#Segmento de edad en Tolima

# 1. Calcular cantidad personas desempleadas entre los 18 - 24 
D1824T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==73)]['FEX_C18'].sum()

D2430T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=24) & (df_d['P6040']<=30) & (df_d['DPTO']==73)]['FEX_C18'].sum()

D3040T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=30) & (df_d['P6040']<=40) & (df_d['DPTO']==73)]['FEX_C18'].sum()

D4050T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=40) & (df_d['P6040']<=50) & (df_d['DPTO']==73)]['FEX_C18'].sum()

D60T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=60) & (df_d['DPTO']==73)]['FEX_C18'].sum()

# 2. Calcular cantidad personas en la PEA en Tolima

PEA1824T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==73)]['FEX_C18'].sum()

PEA2430T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==73)]['FEX_C18'].sum()

PEA3040T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==73)]['FEX_C18'].sum()

PEA4050T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==73)]['FEX_C18'].sum()

PEA60T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==73)]['FEX_C18'].sum()

# 3. Calcular la tasa de desempleo en Tolima

print(f'=======Tasa de desempleo en Tolima=======')

TD1824T = D1824T/PEA1824T
print(f'Tasa de Desempleo en personas entre los 18 - 24 del Tolima: {TD1824T:.2%}')

TD2430T = D2430T/PEA2430T
print(f'Tasa de Desempleo en personas entre los 24 - 30 del Tolima: {TD2430T:.2%}%')

TD3040T = D3040T/PEA3040T
print(f'Tasa de Desempleo en personas entre los 30 - 40 del Tolima: {TD3040T:.2%}')

TD4050T = D4050T/PEA4050T
print(f'Tasa de Desempleo en personas entre los 40 - 50 del Tolima: {TD4050T:.2%}')

TD60T = D60T/PEA60T
print(f'Tasa de Desempleo en personas mayores a 60 del Tolima: {TD60T:.2%}\n')

=======Tasa de desempleo en Tolima=======
Tasa de Desempleo en personas entre los 18 - 24 del Tolima: 19.82%
Tasa de Desempleo en personas entre los 24 - 30 del Tolima: 13.88%%
Tasa de Desempleo en personas entre los 30 - 40 del Tolima: 12.25%
Tasa de Desempleo en personas entre los 40 - 50 del Tolima: 8.64%
Tasa de Desempleo en personas mayores a 60 del Tolima: 9.46%

In [ ]:
#la tasa de desempelo mas alta del Tolima se encuentra en el grupo de 18-24 años (19.82%)
#la tasa con menor tasa de desempleo son los de 40-50 años (8.64%)

In [22]:
#Segmento de edad en Caldas

# 1. Calcular cantidad personas desempleadas entre los 18 - 24 
D1824C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==17)]['FEX_C18'].sum()

D2430C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=24) & (df_d['P6040']<=30) & (df_d['DPTO']==17)]['FEX_C18'].sum()

D3040C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=30) & (df_d['P6040']<=40) & (df_d['DPTO']==17)]['FEX_C18'].sum()

D4050C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=40) & (df_d['P6040']<=50) & (df_d['DPTO']==17)]['FEX_C18'].sum()

D60C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=60) & (df_d['DPTO']==17)]['FEX_C18'].sum()

# 2. Calcular cantidad personas en la PEA en Caldas

PEA1824C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

PEA2430C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=24) & (df_ft['P6040']<=30) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

PEA3040C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=30) & (df_ft['P6040']<=40) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

PEA4050C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=40) & (df_ft['P6040']<=50) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

PEA60C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=60) & (df_ft['DPTO']==17)]['FEX_C18'].sum()

# 3. Calcular la tasa de desempleo en Caldas

print(f'=======Tasa de desempleo en Caldas=======')

TD1824C = D1824C/PEA1824C
print(f'Tasa de Desempleo en personas entre los 18 - 24 del Caldas: {TD1824C:.2%}')

TD2430C = D2430C/PEA2430C
print(f'Tasa de Desempleo en personas entre los 24 - 30 del Caldas: {TD2430C:.2%}%')

TD3040C = D3040C/PEA3040C
print(f'Tasa de Desempleo en personas entre los 30 - 40 del Caldas: {TD3040C:.2%}')

TD4050C = D4050C/PEA4050C
print(f'Tasa de Desempleo en personas entre los 40 - 50 del Caldas: {TD4050C:.2%}')

TD60C = D60C/PEA60C
print(f'Tasa de Desempleo en personas mayores a 60 del Caldas: {TD60C:.2%}\n')

=======Tasa de desempleo en Caldas=======
Tasa de Desempleo en personas entre los 18 - 24 del Caldas: 9.34%
Tasa de Desempleo en personas entre los 24 - 30 del Caldas: 6.44%%
Tasa de Desempleo en personas entre los 30 - 40 del Caldas: 5.72%
Tasa de Desempleo en personas entre los 40 - 50 del Caldas: 5.12%
Tasa de Desempleo en personas mayores a 60 del Caldas: 4.06%

In [ ]:
#la tasa de desempleo mas alta de Caldas se encuentran en el grupos 18-24 años (9.34%)
#la tasa con menor tasa de desempleo son los mayores de 60 años (4.06%)

In [ ]:
#4.Entre Risaralda, Caldas , Tolima y Quindío, cuál es el departamento con menor tasa de desempleo de mujeres entre los 18 y los 25 años ?

In [23]:
# Calcular la tasa de desempleo de mujeres entre los 18 - 24 en el Quindio
D1824Q = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==63) & (df_d['P3271']==2)]['FEX_C18'].sum()

PEA1824Q = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==63) & (df_ft['P3271']==2)]['FEX_C18'].sum()

print(f'=======Tasa de desempleo de mujeres en el Quindio=======')

TD1824Q = D1824Q/PEA1824Q
print(f'Tasa de Desempleo de mujeres entre los 18 - 24 del Quindio: {TD1824Q:.2%}')

=======Tasa de desempleo de mujeres en el Quindio=======
Tasa de Desempleo de mujeres entre los 18 - 24 del Quindio: 6.36%

In [24]:
# Calcular la tasa de desempleo de mujeres entre los 18 - 24 en el Risaralda
D1824R = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==66) & (df_d['P3271']==2)]['FEX_C18'].sum()

PEA1824R = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==66) & (df_ft['P3271']==2)]['FEX_C18'].sum()

print(f'=======Tasa de desempleo de mujeres en el Risaralda=======')

TD1824R = D1824R/PEA1824R
print(f'Tasa de Desempleo de mujeres entre los 18 - 24 del Risaralda: {TD1824R:.2%}')

=======Tasa de desempleo de mujeres en el Risaralda=======
Tasa de Desempleo de mujeres entre los 18 - 24 del Risaralda: 23.64%

In [25]:
# 1. Calcular la tasa de desempleo de mujeres entre los 18 - 24 en el Caldas
D1824C = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==17) & (df_d['P3271']==2)]['FEX_C18'].sum()

PEA1824C = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==17) & (df_ft['P3271']==2)]['FEX_C18'].sum()

print(f'=======Tasa de desempleo de mujeres en el Caldas=======')

TD1824C = D1824C/PEA1824C
print(f'Tasa de Desempleo de mujeres entre los 18 - 24 del Caldas: {TD1824C:.2%}')

=======Tasa de desempleo de mujeres en el Caldas=======
Tasa de Desempleo de mujeres entre los 18 - 24 del Caldas: 10.98%

In [26]:
# 1. Calcular la tasa de desempleo de mujeres entre los 18 - 24 en el Tolima
D1824T = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==73) & (df_d['P3271']==2)]['FEX_C18'].sum()

PEA1824T = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==73) & (df_ft['P3271']==2)]['FEX_C18'].sum()

print(f'=======Tasa de desempleo de mujeres en el Tolima=======')

TD1824T = D1824T/PEA1824T
print(f'Tasa de Desempleo de mujeres entre los 18 - 24 del Tolima: {TD1824T:.2%}')

=======Tasa de desempleo de mujeres en el Tolima=======
Tasa de Desempleo de mujeres entre los 18 - 24 del Tolima: 25.13%

In [ ]:
#Entre los 4 departamentos el que cuenta con la menor tasa de desempleo es el Quindio con una tasa de desempleo de mujeres entre los 18-24 años (6.36%)

In [ ]:
#5.¿Cuántos hombres y mujeres hay en edad de trabajar en el quindio ? ¿Qué porcentaje de la población total representan ?

In [43]:
# población total nacional 
pt_quindio = df_cgsse[(df_cgsse["DPTO"]==63)]['FEX_C18'].sum()

#POBLACION EN EDAD DE TRABAJAR 
PETH = df_cgsse[(df_cgsse['P6040']>=15) & (df_cgsse['DPTO']==63) & (df_cgsse['P3271']==1)]['FEX_C18'].sum()
print(f"Los hombres en edad de trabajar para el Quindio es de {PETH} ")

#POBLACION EN EDAD DE TRABAJAR 
PETM = df_cgsse[(df_cgsse['P6040']>=15) & (df_cgsse['DPTO']==63) & (df_cgsse['P3271']==2)]['FEX_C18'].sum()
print(f"La población en edad de trabajar para Colombia es de {PETM} \n")

# Porcentaje de la población que representan los hombres y mujeres del Quindio en edad de trabajar
porcentaje_hombres_quindio = (PETH / pt_quindio)
print(f"En el departamento del Quindio el porcentaje de hombres en edad de trabajar es de: {porcentaje_hombres_quindio:.2%}")
porcentaje_mujeres_quindio = (PETM / pt_quindio) 
print(f"En el departamento del Quindio el porcentaje de mujeres en edad de trabajar es de: {porcentaje_mujeres_quindio:.2%}")

Los hombres en edad de trabajar para el Quindio es de 247037.510834763
La población en edad de trabajar para Colombia es de 261387.92755063402

En el departamento del Quindio el porcentaje de hombres en edad de trabajar es de: 40.96%
En el departamento del Quindio el porcentaje de mujeres en edad de trabajar es de: 43.34%

In [ ]:
#6. ¿Qué porcentaje de la población del Tolima está en edad de trabajar ?

In [44]:
# 1. Filtrar datos para Tolima (Código 73)
df_tolima = df_cgsse[df_cgsse["DPTO"] == 73].copy()

# 2. Identificar la PET (15 años o más)
df_tolima['es_PET'] = df_tolima['P6040'] >= 15

# 3. Sumar poblaciones usando el factor de expansión (FEX_C18)
poblacion_total_tolima = df_tolima['FEX_C18'].sum()
poblacion_pet_tolima = df_tolima[df_tolima['es_PET'] == True]['FEX_C18'].sum()

# 4. Calcular el porcentaje
porcentaje_pet = (poblacion_pet_tolima / poblacion_total_tolima) * 100

print(f"En Tolima el porcentaje de la población en edad de trabajar es de: {porcentaje_pet:.2f}%")

En Tolima el porcentaje de la población en edad de trabajar es de: 77.01%

In [ ]:
#7.¿ Qué porcentaje de la población de Risaralda es población económicamente inactiva ?

In [45]:
PEIR= df_ft[(df_ft["FFT"]==1) & (df_ft['DPTO']==66)]["FEX_C18"].sum()
PETR= df_cgsse[(df_cgsse['DPTO']==66)]["FEX_C18"].sum()
PEIR1= PEIR/PETR
print(f'La población en edad de trabajar en Risaralda es de: {PETR}')
print(f'En Risarralda el porcentaje de la población económicamente inactiva(PEI) es de: {PEIR1:.2%}')

La población en edad de trabajar en Risaralda es de: 1025240.9423573611
En Risarralda el porcentaje de la población económicamente inactiva(PEI) es de: 32.46%

In [ ]:
# 8. ¿Cuántas personas hay en el Quindío en condición de desempleo entre los 18 y los 30 años ?

In [30]:
# 1. Calcular el desempleo entre los 18 - 30 en el Quindio
D1830Q = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=30) & (df_d['DPTO']==63)]['FEX_C18'].sum()

print(f'El desempleo entre los 18 y los 30 en el Quindio: {D1830Q}')

El desempleo entre los 18 y los 30 en el Quindio: 9479.632579867999

In [ ]:
# 9.¿Cuántas personas hay ocupadas en el departamento del Tolima , cuyas edades están entre los 20 y los 25 años , qué porcentaje de la población total del Tolima representan ?

In [31]:
# 1. Calcular las personas ocupadas en el Tolima entre los 20 - 25 

PTQ = df_cgsse[df_cgsse['DPTO']==63]['FEX_C18'].sum()


#Primero hay que anexar la p3271 a la tabla de desempleados
df_o = pd.merge(df_ocupados, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN','P6040']], 
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

D1830Q = df_o[ (df_o['P6040']>=20) & (df_o['P6040']<=25) & (df_o['DPTO']==73)]['FEX_C18'].sum()

PPTT = D1830Q/ PTQ

print(f'Las personas ocupadas entre los 20 y 25 años en el Tolima: {D1830Q}')
print(f'El porcentaje de personas ocupadas entre los 20 y 25 años en el Tolima: {PPTT:.2%}')

Las personas ocupadas entre los 20 y 25 años en el Tolima: 63257.06760223999
El porcentaje de personas ocupadas entre los 20 y 25 años en el Tolima: 10.49%